#!/usr/bin/env python3
"""CLI utility to configure and manage MiroFish infrastructure locally."""

import argparse
import datetime
import shutil
import socket
import subprocess
import sys
from pathlib import Path

from infra_form_server import run_form_server

ROOT = Path(__file__).resolve().parents[1]
ENV_PATH = ROOT / ".env"
GENERATED_DIR = ROOT / ".infra"
GENERATED_COMPOSE_PATH = GENERATED_DIR / "docker-compose.generated.yml"

DISALLOWED_PORTS = {
    8000,
    8080,
    3000,
    4000,
    6006,
    6660,
    6661,
    6662,
    6663,
    6664,
    6665,
    6666,
    6667,
    6668,
    6669,
}


def run_command(cmd: list[str], check: bool = True) -> int:
    """Run a command from project root and optionally enforce success."""
    process = subprocess.run(cmd, cwd=ROOT, check=False)
    if check and process.returncode != 0:
        raise RuntimeError(f"Command failed: {' '.join(cmd)}")
    return process.returncode


def parse_env_file(path: Path) -> dict[str, str]:
    """Parse a dotenv-style file into key/value mappings."""
    values: dict[str, str] = {}
    if not path.exists():
        return values

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def write_env_file(values: dict[str, str]) -> None:
    """Write a generated .env file and backup any existing version."""
    if ENV_PATH.exists():
        timestamp = datetime.datetime.now().strftime("%Y%m%d%H%M%S")
        backup_path = ENV_PATH.with_suffix(f".env.bak.{timestamp}")
        shutil.copy2(ENV_PATH, backup_path)
        print(f"[info] Existing .env backed up to: {backup_path}")

    lines = [
        "# Generated by scripts/infra_manager.py",
        f"# Generated at: {datetime.datetime.now().isoformat()}",
        "",
        "# Required",
        f"LLM_API_KEY={values['LLM_API_KEY']}",
        f"ZEP_API_KEY={values['ZEP_API_KEY']}",
        "",
        "# Recommended",
        f"LLM_BASE_URL={values['LLM_BASE_URL']}",
        f"LLM_MODEL_NAME={values['LLM_MODEL_NAME']}",
        "",
    ]

    if values.get("LLM_BOOST_ENABLED") == "true":
        lines.extend(
            [
                "# Optional acceleration",
                f"LLM_BOOST_API_KEY={values['LLM_BOOST_API_KEY']}",
                f"LLM_BOOST_BASE_URL={values['LLM_BOOST_BASE_URL']}",
                f"LLM_BOOST_MODEL_NAME={values['LLM_BOOST_MODEL_NAME']}",
                "",
            ]
        )

    ENV_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"[ok] Wrote environment configuration: {ENV_PATH}")


def is_port_in_use(port: int) -> bool:
    """Return True when the provided localhost TCP port is occupied."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        return s.connect_ex(("127.0.0.1", port)) == 0


def validate_port(port: int, label: str) -> None:
    """Validate a port against range, denylist, and current usage."""
    if port <= 0 or port > 65535:
        raise ValueError(f"{label} must be between 1 and 65535")

    if port in DISALLOWED_PORTS:
        raise ValueError(
            f"{label}={port} is disallowed. Use another port."
        )

    if is_port_in_use(port):
        raise ValueError(f"{label}={port} is already in use on localhost")


def ask_text(prompt: str, default: str | None = None, required: bool = False) -> str:
    """Prompt for text input with optional default and required checks."""
    while True:
        suffix = f" [{default}]" if default else ""
        raw = input(f"{prompt}{suffix}: ").strip()
        value = raw if raw else (default or "")

        if required and not value:
            print("[error] This field is required.")
            continue
        return value


def ask_yes_no(prompt: str, default_yes: bool = False) -> bool:
    """Prompt for a yes/no answer and return a boolean result."""
    default_hint = "Y/n" if default_yes else "y/N"
    while True:
        answer = input(f"{prompt} [{default_hint}]: ").strip().lower()
        if not answer:
            return default_yes
        if answer in {"y", "yes"}:
            return True
        if answer in {"n", "no"}:
            return False
        print("[error] Please enter y or n.")


def ask_port(prompt: str, default: int) -> int:
    """Prompt for a valid, available port number."""
    while True:
        raw = ask_text(prompt, default=str(default), required=True)
        try:
            port = int(raw)
            validate_port(port, prompt)
            return port
        except ValueError as exc:
            print(f"[error] {exc}")


def generate_compose(frontend_port: int, backend_port: int) -> None:
    """Generate a docker compose file that maps configured host ports."""
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    content = f"""services:
  mirofish:
    image: ghcr.io/666ghj/mirofish:latest
    container_name: mirofish
    env_file:
      - .env
    ports:
      - \"{frontend_port}:3000\"
      - \"{backend_port}:5001\"
    restart: unless-stopped
    volumes:
      - ./backend/uploads:/app/backend/uploads
"""
    GENERATED_COMPOSE_PATH.write_text(content, encoding="utf-8")
    print(f"[ok] Wrote generated compose file: {GENERATED_COMPOSE_PATH}")


def docker_available() -> bool:
    """Return True when Docker is available in PATH."""
    return shutil.which("docker") is not None


def ensure_docker() -> None:
    """Raise if Docker is not available in the current environment."""
    if not docker_available():
        raise RuntimeError("Docker is required but was not found in PATH")


def compose_cmd(*args: str) -> list[str]:
    """Build a docker compose command targeting the generated file."""
    return [
        "docker",
        "compose",
        "-f",
        str(GENERATED_COMPOSE_PATH),
        *args,
    ]


def ensure_generated_compose_exists() -> None:
    """Raise if setup has not generated the compose file yet."""
    if not GENERATED_COMPOSE_PATH.exists():
        raise RuntimeError(
            f"Generated compose file not found: {GENERATED_COMPOSE_PATH}. Run setup first."
        )


def setup_interactive() -> None:
    """Collect infra inputs interactively and generate local config files."""
    print("== MiroFish Infrastructure Setup ==")
    existing = parse_env_file(ENV_PATH)

    llm_api_key = ask_text(
        "LLM_API_KEY",
        default=existing.get("LLM_API_KEY"),
        required=True,
    )
    zep_api_key = ask_text(
        "ZEP_API_KEY",
        default=existing.get("ZEP_API_KEY"),
        required=True,
    )
    llm_base_url = ask_text(
        "LLM_BASE_URL",
        default=existing.get("LLM_BASE_URL", "https://dashscope.aliyuncs.com/compatible-mode/v1"),
        required=True,
    )
    llm_model_name = ask_text(
        "LLM_MODEL_NAME",
        default=existing.get("LLM_MODEL_NAME", "qwen-plus"),
        required=True,
    )

    frontend_port = ask_port(
        "Frontend host port",
        default=3100,
    )
    backend_port = ask_port(
        "Backend host port",
        default=5101,
    )

    while backend_port == frontend_port:
        print("[error] Frontend and backend ports must be different.")
        backend_port = ask_port("Backend host port", default=5101)

    llm_boost_enabled = ask_yes_no(
        "Enable LLM boost configuration?",
        default_yes=False,
    )

    values: dict[str, str] = {
        "LLM_API_KEY": llm_api_key,
        "ZEP_API_KEY": zep_api_key,
        "LLM_BASE_URL": llm_base_url,
        "LLM_MODEL_NAME": llm_model_name,
        "LLM_BOOST_ENABLED": "true" if llm_boost_enabled else "false",
    }

    if llm_boost_enabled:
        values["LLM_BOOST_API_KEY"] = ask_text(
            "LLM_BOOST_API_KEY",
            default=existing.get("LLM_BOOST_API_KEY"),
            required=True,
        )
        values["LLM_BOOST_BASE_URL"] = ask_text(
            "LLM_BOOST_BASE_URL",
            default=existing.get("LLM_BOOST_BASE_URL"),
            required=True,
        )
        values["LLM_BOOST_MODEL_NAME"] = ask_text(
            "LLM_BOOST_MODEL_NAME",
            default=existing.get("LLM_BOOST_MODEL_NAME"),
            required=True,
        )

    write_env_file(values)
    generate_compose(frontend_port, backend_port)

    print("\n[done] Setup complete.")
    print(f"- Frontend: http://localhost:{frontend_port}")
    print(f"- Backend:  http://localhost:{backend_port}")
    print("- Next: run `uv run python scripts/infra_manager.py up`")


def cmd_up() -> None:
    """Start the managed infrastructure stack in detached mode."""
    ensure_docker()
    ensure_generated_compose_exists()
    run_command(compose_cmd("up", "-d"))
    print("[ok] MiroFish infrastructure is up.")


def cmd_down() -> None:
    """Stop the managed infrastructure stack."""
    ensure_docker()
    ensure_generated_compose_exists()
    run_command(compose_cmd("down"))
    print("[ok] MiroFish infrastructure is down.")


def cmd_restart() -> None:
    """Restart the managed infrastructure stack."""
    ensure_docker()
    ensure_generated_compose_exists()
    run_command(compose_cmd("down"))
    run_command(compose_cmd("up", "-d"))
    print("[ok] MiroFish infrastructure restarted.")


def cmd_status() -> None:
    """Show status for managed compose services."""
    ensure_docker()
    ensure_generated_compose_exists()
    run_command(compose_cmd("ps"))


def cmd_logs(follow: bool = False) -> None:
    """Show compose logs, optionally streaming continuously."""
    ensure_docker()
    ensure_generated_compose_exists()
    args = ["logs"]
    if follow:
        args.append("-f")
    args.append("mirofish")
    run_command(compose_cmd(*args), check=False)


def cmd_doctor() -> None:
    """Print environment checks for prerequisites and generated files."""
    print("== MiroFish Infra Doctor ==")
    print(f"Project root: {ROOT}")
    print(f"Docker in PATH: {'yes' if docker_available() else 'no'}")
    print(f".env exists: {'yes' if ENV_PATH.exists() else 'no'}")
    print(f"generated compose exists: {'yes' if GENERATED_COMPOSE_PATH.exists() else 'no'}")


def build_parser() -> argparse.ArgumentParser:
    """Create and return the CLI argument parser."""
    parser = argparse.ArgumentParser(
        description="MiroFish infrastructure manager with interactive setup form"
    )
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("setup", help="Run interactive setup form")
    sub.add_parser("up", help="Start infrastructure")
    sub.add_parser("down", help="Stop infrastructure")
    sub.add_parser("restart", help="Restart infrastructure")
    sub.add_parser("status", help="Show infrastructure status")

    logs_parser = sub.add_parser("logs", help="Show container logs")
    logs_parser.add_argument("-f", "--follow", action="store_true", help="Follow logs")

    form_parser = sub.add_parser("form", help="Launch tabbed infrastructure + whitelabeling form")
    form_parser.add_argument(
        "--port",
        type=int,
        default=8777,
        help="Port for local form UI (default: 8777)",
    )

    whitelabel_parser = sub.add_parser(
        "whitelabel",
        help="Launch branding whitelist/replacement form",
    )
    whitelabel_parser.add_argument(
        "--port",
        type=int,
        default=8777,
        help="Port for local form UI (default: 8777)",
    )

    sub.add_parser("doctor", help="Check local prerequisites and generated files")
    return parser


def main() -> int:
    """Dispatch CLI commands and normalize error handling."""
    parser = build_parser()
    args = parser.parse_args()

    try:
        if args.command == "setup":
            setup_interactive()
        elif args.command == "up":
            cmd_up()
        elif args.command == "down":
            cmd_down()
        elif args.command == "restart":
            cmd_restart()
        elif args.command == "status":
            cmd_status()
        elif args.command == "logs":
            cmd_logs(follow=args.follow)
        elif args.command == "form":
            run_form_server(args.port)
        elif args.command == "whitelabel":
            run_form_server(args.port)
        elif args.command == "doctor":
            cmd_doctor()
        else:
            parser.print_help()
            return 1
        return 0
    except KeyboardInterrupt:
        print("\n[info] Interrupted by user")
        return 130
    except (RuntimeError, ValueError, OSError, subprocess.SubprocessError) as exc:
        print(f"[fatal] {exc}")
        return 1


if __name__ == "__main__":
    sys.exit(main())
