#!/usr/bin/env python3
import argparse
import datetime
import html
import json
import math
import os
import re
import socket
import urllib.parse
import xml.etree.ElementTree as ET
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ENV_PATH = ROOT / ".env"
GENERATED_DIR = ROOT / ".infra"
GENERATED_COMPOSE_PATH = GENERATED_DIR / "docker-compose.generated.yml"
WHITELIST_PATH = GENERATED_DIR / "branding_whitelist.json"
ASSET_BACKUP_DIR = GENERATED_DIR / "asset_backups"

DISALLOWED_PORTS = {
    8000,
    8080,
    3000,
    4000,
    6006,
    6660,
    6661,
    6662,
    6663,
    6664,
    6665,
    6666,
    6667,
    6668,
    6669,
}

IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".gif", ".bmp", ".webp", ".svg", ".ico"}
TEXT_SEARCH_EXTENSIONS = {
    ".md",
    ".vue",
    ".html",
    ".js",
    ".ts",
    ".css",
    ".scss",
    ".json",
    ".yml",
    ".yaml",
    ".py",
}
BRANDING_HINTS = ("logo", "brand", "icon", "favicon", "cover", "banner", "shanda")
MAX_UPLOAD_MB = 10
RATIO_TOLERANCE = 0.03


def parse_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def write_env_file(values: dict[str, str]) -> None:
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    if ENV_PATH.exists():
        ts = datetime.datetime.now().strftime("%Y%m%d%H%M%S")
        backup_path = GENERATED_DIR / f"env.backup.{ts}.txt"
        backup_path.write_text(ENV_PATH.read_text(encoding="utf-8"), encoding="utf-8")

    lines = [
        "# Generated by branding/infrastructure form",
        f"# Generated at: {datetime.datetime.now().isoformat()}",
        "",
        f"LLM_API_KEY={values['LLM_API_KEY']}",
        f"ZEP_API_KEY={values['ZEP_API_KEY']}",
        f"LLM_BASE_URL={values['LLM_BASE_URL']}",
        f"LLM_MODEL_NAME={values['LLM_MODEL_NAME']}",
        "",
    ]

    if values.get("LLM_BOOST_ENABLED") == "true":
        lines.extend(
            [
                f"LLM_BOOST_API_KEY={values.get('LLM_BOOST_API_KEY', '')}",
                f"LLM_BOOST_BASE_URL={values.get('LLM_BOOST_BASE_URL', '')}",
                f"LLM_BOOST_MODEL_NAME={values.get('LLM_BOOST_MODEL_NAME', '')}",
                "",
            ]
        )

    ENV_PATH.write_text("\n".join(lines), encoding="utf-8")


def generate_compose(frontend_port: int, backend_port: int) -> None:
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    content = f"""services:
  mirofish:
    image: ghcr.io/666ghj/mirofish:latest
    container_name: mirofish
    env_file:
      - .env
    ports:
      - \"{frontend_port}:3000\"
      - \"{backend_port}:5001\"
    restart: unless-stopped
    volumes:
      - ./backend/uploads:/app/backend/uploads
"""
    GENERATED_COMPOSE_PATH.write_text(content, encoding="utf-8")


def is_port_in_use(port: int) -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        return s.connect_ex(("127.0.0.1", port)) == 0


def validate_port(port: int, label: str) -> None:
    if port <= 0 or port > 65535:
        raise ValueError(f"{label} must be between 1 and 65535")
    if port in DISALLOWED_PORTS:
        raise ValueError(f"{label}={port} is disallowed")
    if is_port_in_use(port):
        raise ValueError(f"{label}={port} is already in use")


def ratio_text(width: int | None, height: int | None) -> str:
    if not width or not height:
        return "unknown"
    g = math.gcd(width, height)
    return f"{width // g}:{height // g}"


def _parse_svg_size(path: Path) -> tuple[int | None, int | None]:
    try:
        root = ET.fromstring(path.read_text(encoding="utf-8", errors="ignore"))
    except Exception:
        return None, None

    def n(v: str | None) -> int | None:
        if not v:
            return None
        cleaned = re.sub(r"[^0-9.]+", "", v)
        if not cleaned:
            return None
        try:
            return int(float(cleaned))
        except ValueError:
            return None

    width = n(root.attrib.get("width"))
    height = n(root.attrib.get("height"))
    if width and height:
        return width, height

    view_box = root.attrib.get("viewBox")
    if view_box:
        parts = view_box.replace(",", " ").split()
        if len(parts) == 4:
            try:
                return int(float(parts[2])), int(float(parts[3]))
            except ValueError:
                return None, None
    return None, None


def parse_image_size(path: Path) -> tuple[int | None, int | None]:
    suffix = path.suffix.lower()
    data = path.read_bytes()

    if suffix == ".png" and len(data) >= 24 and data[:8] == b"\x89PNG\r\n\x1a\n":
        return int.from_bytes(data[16:20], "big"), int.from_bytes(data[20:24], "big")

    if suffix in {".jpg", ".jpeg"} and data[:2] == b"\xff\xd8":
        i = 2
        while i + 9 < len(data):
            if data[i] != 0xFF:
                i += 1
                continue
            marker = data[i + 1]
            i += 2
            if marker in {0xD8, 0xD9}:
                continue
            if i + 2 > len(data):
                break
            seg_len = int.from_bytes(data[i:i + 2], "big")
            if seg_len < 2 or i + seg_len > len(data):
                break
            if marker in {0xC0, 0xC1, 0xC2, 0xC3, 0xC5, 0xC6, 0xC7, 0xC9, 0xCA, 0xCB, 0xCD, 0xCE, 0xCF}:
                h = int.from_bytes(data[i + 3:i + 5], "big")
                w = int.from_bytes(data[i + 5:i + 7], "big")
                return w, h
            i += seg_len

    if suffix == ".gif" and len(data) >= 10 and data[:3] == b"GIF":
        return int.from_bytes(data[6:8], "little"), int.from_bytes(data[8:10], "little")

    if suffix == ".bmp" and len(data) >= 26 and data[:2] == b"BM":
        return int.from_bytes(data[18:22], "little"), abs(int.from_bytes(data[22:26], "little", signed=True))

    if suffix == ".webp" and len(data) >= 30 and data[:4] == b"RIFF" and data[8:12] == b"WEBP":
        chunk = data[12:16]
        if chunk == b"VP8X" and len(data) >= 30:
            w = 1 + int.from_bytes(data[24:27], "little")
            h = 1 + int.from_bytes(data[27:30], "little")
            return w, h

    if suffix == ".ico" and len(data) >= 8:
        w = data[6] or 256
        h = data[7] or 256
        return w, h

    if suffix == ".svg":
        return _parse_svg_size(path)

    return None, None


def find_text_references(asset_rel: str) -> list[str]:
    refs: list[str] = []
    needle = asset_rel.replace("\\", "/")
    basename = Path(asset_rel).name

    for path in ROOT.rglob("*"):
        if not path.is_file() or path.suffix.lower() not in TEXT_SEARCH_EXTENSIONS:
            continue
        try:
            content = path.read_text(encoding="utf-8", errors="ignore")
        except Exception:
            continue
        if needle in content or basename in content:
            refs.append(str(path.relative_to(ROOT)))
        if len(refs) >= 8:
            break
    return refs


def discover_image_assets() -> list[dict[str, object]]:
    assets: list[dict[str, object]] = []
    for path in ROOT.rglob("*"):
        if not path.is_file() or path.suffix.lower() not in IMAGE_EXTENSIONS:
            continue
        rel = str(path.relative_to(ROOT)).replace("\\", "/")
        lower = rel.lower()
        width, height = parse_image_size(path)
        refs = find_text_references(rel)
        is_branding = any(h in lower for h in BRANDING_HINTS) or bool(refs)

        assets.append(
            {
                "rel_path": rel,
                "size_bytes": path.stat().st_size,
                "width": width,
                "height": height,
                "ratio": ratio_text(width, height),
                "is_branding": is_branding,
                "references": refs,
            }
        )

    assets.sort(key=lambda x: str(x["rel_path"]))
    return assets


def default_whitelist(assets: list[dict[str, object]]) -> set[str]:
    items = set()
    for asset in assets:
        rel = str(asset["rel_path"])
        if asset.get("is_branding"):
            items.add(rel)
    return items


def load_whitelist(assets: list[dict[str, object]]) -> set[str]:
    if WHITELIST_PATH.exists():
        try:
            data = json.loads(WHITELIST_PATH.read_text(encoding="utf-8"))
            listed = data.get("assets", [])
            return {str(x) for x in listed}
        except Exception:
            pass
    wl = default_whitelist(assets)
    save_whitelist(wl)
    return wl


def save_whitelist(items: set[str]) -> None:
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    payload = {"assets": sorted(items), "max_upload_mb": MAX_UPLOAD_MB}
    WHITELIST_PATH.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def safe_asset_path(asset_rel: str) -> Path:
    target = (ROOT / asset_rel).resolve()
    root_resolved = ROOT.resolve()
    if root_resolved not in [target] and root_resolved not in target.parents:
        raise ValueError("Asset path is outside project root")
    if not target.exists() or not target.is_file():
        raise ValueError("Target asset does not exist")
    if target.suffix.lower() not in IMAGE_EXTENSIONS:
        raise ValueError("Target must be an image asset")
    return target


def replace_asset(asset_rel: str, upload_name: str, upload_bytes: bytes, whitelist: set[str]) -> str:
    if asset_rel not in whitelist:
        raise ValueError("Asset is not whitelisted for replacement")

    target = safe_asset_path(asset_rel)
    if not upload_bytes:
        raise ValueError("No file uploaded")

    if len(upload_bytes) > MAX_UPLOAD_MB * 1024 * 1024:
        raise ValueError(f"Upload too large (> {MAX_UPLOAD_MB}MB)")

    upload_suffix = Path(upload_name).suffix.lower()
    if upload_suffix not in IMAGE_EXTENSIONS:
        raise ValueError("Uploaded file type is not allowed")

    temp_path = GENERATED_DIR / f"upload-check-{datetime.datetime.now().strftime('%Y%m%d%H%M%S%f')}{upload_suffix}"
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    temp_path.write_bytes(upload_bytes)

    try:
        old_w, old_h = parse_image_size(target)
        new_w, new_h = parse_image_size(temp_path)

        if old_w and old_h and new_w and new_h:
            old_ratio = old_w / old_h
            new_ratio = new_w / new_h
            if abs(old_ratio - new_ratio) > RATIO_TOLERANCE:
                raise ValueError(
                    f"Aspect ratio mismatch: old={ratio_text(old_w, old_h)} new={ratio_text(new_w, new_h)}"
                )

        backup_stamp = datetime.datetime.now().strftime("%Y%m%d%H%M%S")
        backup_target = ASSET_BACKUP_DIR / backup_stamp / asset_rel
        backup_target.parent.mkdir(parents=True, exist_ok=True)
        backup_target.write_bytes(target.read_bytes())

        target.write_bytes(upload_bytes)
    finally:
        if temp_path.exists():
            temp_path.unlink()

    return f"Replaced {asset_rel} (backup saved)"


def read_urlencoded(handler: BaseHTTPRequestHandler) -> dict[str, str]:
    length = int(handler.headers.get("Content-Length", "0"))
    payload = handler.rfile.read(length).decode("utf-8", errors="ignore")
    parsed = urllib.parse.parse_qs(payload)
    return {k: (v[-1] if v else "") for k, v in parsed.items()}


def render_page(message: str = "", active_tab: str = "infra") -> str:
    assets = discover_image_assets()
    whitelist = load_whitelist(assets)
    env = parse_env_file(ENV_PATH)

    branding_assets = [a for a in assets if a["is_branding"]]

    def asset_rows(items: list[dict[str, object]]) -> str:
        rows = []
        for asset in items:
            rel = str(asset["rel_path"])
            refs = asset["references"]
            refs_text = "<br>".join(html.escape(str(x)) for x in refs) if refs else "-"
            whitelisted = rel in whitelist
            action_html = (
                f"<form method='post' action='/api/whitelist/remove' class='inline-form'>"
                f"<input type='hidden' name='asset_rel' value='{html.escape(rel)}'>"
                f"<button type='submit' class='danger'>Remove</button></form>"
                if whitelisted
                else f"<form method='post' action='/api/whitelist/add' class='inline-form'>"
                f"<input type='hidden' name='asset_rel' value='{html.escape(rel)}'>"
                f"<button type='submit'>Allow</button></form>"
            )

            replace_html = (
                f"<form method='post' action='/api/replace' enctype='multipart/form-data' class='upload-form'>"
                f"<input type='hidden' name='asset_rel' value='{html.escape(rel)}'>"
                f"<input type='file' name='replacement' required>"
                f"<button type='submit'>Replace</button>"
                f"</form>"
                if whitelisted
                else "<span class='muted'>Whitelist first</span>"
            )

            rows.append(
                "<tr>"
                f"<td><code>{html.escape(rel)}</code></td>"
                f"<td>{asset['width'] or '-'} × {asset['height'] or '-'}</td>"
                f"<td>{html.escape(str(asset['ratio']))}</td>"
                f"<td>{asset['size_bytes']}</td>"
                f"<td>{refs_text}</td>"
                f"<td>{'yes' if whitelisted else 'no'}<br>{action_html}</td>"
                f"<td>{replace_html}</td>"
                "</tr>"
            )
        return "\n".join(rows)

    infra_active = "active" if active_tab == "infra" else ""
    branding_active = "active" if active_tab == "branding" else ""

    return f"""<!doctype html>
<html>
<head>
  <meta charset='utf-8'>
  <meta name='viewport' content='width=device-width, initial-scale=1'>
  <title>MiroFish Infrastructure + Whitelabeling Form</title>
  <style>
    body {{ font-family: sans-serif; margin: 0; background: #f5f7fb; color: #111; }}
    .wrap {{ max-width: 1280px; margin: 0 auto; padding: 20px; }}
    .tabs {{ display: flex; gap: 8px; margin-bottom: 16px; }}
    .tab {{ padding: 10px 14px; border: 1px solid #c7d0e0; border-radius: 8px; cursor: pointer; background: #fff; text-decoration: none; color: #111; }}
    .tab.active {{ background: #0f172a; color: #fff; border-color: #0f172a; }}
    .panel {{ display: none; background: #fff; border: 1px solid #dbe3f0; border-radius: 12px; padding: 16px; }}
    .panel.active {{ display: block; }}
    .grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }}
    label {{ display: flex; flex-direction: column; gap: 6px; font-size: 14px; }}
    input[type='text'], input[type='number'] {{ padding: 8px; border: 1px solid #c7d0e0; border-radius: 8px; }}
    table {{ width: 100%; border-collapse: collapse; font-size: 13px; }}
    th, td {{ border: 1px solid #e2e8f0; padding: 8px; vertical-align: top; }}
    th {{ background: #f8fafc; text-align: left; }}
    code {{ white-space: nowrap; }}
    .actions {{ margin-top: 14px; display: flex; gap: 8px; }}
    button {{ padding: 8px 12px; border: 1px solid #b9c4d8; background: #fff; border-radius: 8px; cursor: pointer; }}
    button.primary {{ background: #0f172a; color: #fff; border-color: #0f172a; }}
    button.danger {{ background: #7f1d1d; color: #fff; border-color: #7f1d1d; }}
    .inline-form, .upload-form {{ display: inline-flex; gap: 6px; align-items: center; margin-top: 4px; }}
    .muted {{ color: #64748b; }}
    .msg {{ margin-bottom: 12px; padding: 10px; border-radius: 8px; background: #ecfeff; border: 1px solid #a5f3fc; }}
    .small {{ font-size: 12px; color: #475569; }}
  </style>
</head>
<body>
  <div class='wrap'>
    <h2>MiroFish Turnkey Infra + Whitelabeling</h2>
    <p class='small'>Public-safe flow: whitelist assets first, then replace via browse button. Ratio checks enforce visual compatibility.</p>
    {f"<div class='msg'>{html.escape(message)}</div>" if message else ""}

    <div class='tabs'>
      <a class='tab {infra_active}' href='/?tab=infra'>Infrastructure</a>
      <a class='tab {branding_active}' href='/?tab=branding'>Branding</a>
    </div>

    <section id='infra' class='panel {infra_active}'>
      <h3>Infrastructure Form</h3>
      <form method='post' action='/api/setup'>
        <div class='grid'>
          <label>LLM_API_KEY<input type='text' name='LLM_API_KEY' value='{html.escape(env.get("LLM_API_KEY", ""))}' required></label>
          <label>ZEP_API_KEY<input type='text' name='ZEP_API_KEY' value='{html.escape(env.get("ZEP_API_KEY", ""))}' required></label>
          <label>LLM_BASE_URL<input type='text' name='LLM_BASE_URL' value='{html.escape(env.get("LLM_BASE_URL", "https://dashscope.aliyuncs.com/compatible-mode/v1"))}' required></label>
          <label>LLM_MODEL_NAME<input type='text' name='LLM_MODEL_NAME' value='{html.escape(env.get("LLM_MODEL_NAME", "qwen-plus"))}' required></label>
          <label>Frontend host port<input type='number' name='frontend_port' min='1' max='65535' value='3100' required></label>
          <label>Backend host port<input type='number' name='backend_port' min='1' max='65535' value='5101' required></label>
        </div>
        <div class='actions'><button class='primary' type='submit'>Save .env + compose</button></div>
      </form>
    </section>

    <section id='branding' class='panel {branding_active}'>
      <h3>Branding Elements</h3>
      <p class='small'>Detected branding items: {len(branding_assets)} | All image assets: {len(assets)} | Whitelisted: {len(whitelist)}</p>
      <table>
        <thead>
          <tr><th>Asset</th><th>Dimensions</th><th>Ratio</th><th>Bytes</th><th>References</th><th>Whitelist</th><th>Replace</th></tr>
        </thead>
        <tbody>
          {asset_rows(branding_assets)}
        </tbody>
      </table>

      <h3 style='margin-top:18px;'>All Image Assets</h3>
      <table>
        <thead>
          <tr><th>Asset</th><th>Dimensions</th><th>Ratio</th><th>Bytes</th><th>References</th><th>Whitelist</th><th>Replace</th></tr>
        </thead>
        <tbody>
          {asset_rows(assets)}
        </tbody>
      </table>
    </section>
  </div>

</body>
</html>
"""


class FormHandler(BaseHTTPRequestHandler):
    def _redirect(self, message: str, tab: str = "infra") -> None:
        location = "/?tab=" + urllib.parse.quote(tab) + "&msg=" + urllib.parse.quote(message)
        self.send_response(303)
        self.send_header("Location", location)
        self.end_headers()

    def _read_form_urlencoded(self) -> dict[str, str]:
        length = int(self.headers.get("Content-Length", "0"))
        raw = self.rfile.read(length).decode("utf-8", errors="ignore")
        parsed = urllib.parse.parse_qs(raw)
        return {k: (v[-1] if v else "") for k, v in parsed.items()}

    def do_GET(self) -> None:
        parsed = urllib.parse.urlparse(self.path)
        query = urllib.parse.parse_qs(parsed.query)
        tab = (query.get("tab", ["infra"])[0] or "infra").strip()
        msg = (query.get("msg", [""])[0] or "").strip()
        html_doc = render_page(message=msg, active_tab=tab)

        self.send_response(200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(html_doc.encode("utf-8"))))
        self.end_headers()
        self.wfile.write(html_doc.encode("utf-8"))

    def do_POST(self) -> None:
        if self.path == "/api/setup":
            try:
                data = self._read_form_urlencoded()
                fp = int(data.get("frontend_port", "0"))
                bp = int(data.get("backend_port", "0"))

                if fp == bp:
                    raise ValueError("Frontend and backend ports must be different")
                validate_port(fp, "Frontend host port")
                validate_port(bp, "Backend host port")

                values = {
                    "LLM_API_KEY": data.get("LLM_API_KEY", "").strip(),
                    "ZEP_API_KEY": data.get("ZEP_API_KEY", "").strip(),
                    "LLM_BASE_URL": data.get("LLM_BASE_URL", "").strip(),
                    "LLM_MODEL_NAME": data.get("LLM_MODEL_NAME", "").strip(),
                    "LLM_BOOST_ENABLED": "false",
                }
                if not values["LLM_API_KEY"] or not values["ZEP_API_KEY"]:
                    raise ValueError("LLM_API_KEY and ZEP_API_KEY are required")

                write_env_file(values)
                generate_compose(fp, bp)
                self._redirect("Saved infrastructure config", tab="infra")
            except Exception as exc:
                self._redirect(f"Error: {exc}", tab="infra")
            return

        if self.path in {"/api/whitelist/add", "/api/whitelist/remove"}:
            try:
                data = self._read_form_urlencoded()
                asset_rel = data.get("asset_rel", "").strip()
                if not asset_rel:
                    raise ValueError("asset_rel required")

                assets = discover_image_assets()
                known = {str(a["rel_path"]) for a in assets}
                if asset_rel not in known:
                    raise ValueError("unknown asset")

                wl = load_whitelist(assets)
                if self.path.endswith("/add"):
                    wl.add(asset_rel)
                else:
                    wl.discard(asset_rel)
                save_whitelist(wl)
                self._redirect("Whitelist updated", tab="branding")
            except Exception as exc:
                self._redirect(f"Error: {exc}", tab="branding")
            return

        if self.path == "/api/replace":
            try:
                ctype = self.headers.get("Content-Type", "")
                if "multipart/form-data" not in ctype:
                    raise ValueError("multipart/form-data required")

                boundary_match = re.search(r"boundary=(.+)", ctype)
                if not boundary_match:
                    raise ValueError("multipart boundary missing")

                length = int(self.headers.get("Content-Length", "0"))
                body = self.rfile.read(length)
                boundary = boundary_match.group(1).encode()
                parts = body.split(b"--" + boundary)

                asset_rel = ""
                upload_name = ""
                upload_bytes = b""

                for part in parts:
                    if b"Content-Disposition" not in part:
                        continue
                    header, _, content = part.partition(b"\r\n\r\n")
                    header_text = header.decode("utf-8", errors="ignore")
                    content = content.rstrip(b"\r\n")
                    if 'name="asset_rel"' in header_text:
                        asset_rel = content.decode("utf-8", errors="ignore").strip()
                    elif 'name="replacement"' in header_text:
                        m = re.search(r'filename="([^"]*)"', header_text)
                        upload_name = m.group(1) if m else "upload.bin"
                        upload_bytes = content

                if not asset_rel:
                    raise ValueError("asset_rel missing")

                assets = discover_image_assets()
                wl = load_whitelist(assets)
                message = replace_asset(asset_rel, upload_name, upload_bytes, wl)
                self._redirect(message, tab="branding")
            except Exception as exc:
                self._redirect(f"Error: {exc}", tab="branding")
            return

        self._redirect("Unknown endpoint", tab="infra")


def run_form_server(port: int) -> None:
    validate_port(port, "Form server port")
    server = HTTPServer(("0.0.0.0", port), FormHandler)
    print(f"[ok] Form UI: http://localhost:{port}")
    print("[info] Tabs: Infrastructure + Branding (whitelabeling)")
    print("[info] Press Ctrl+C to stop")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="MiroFish tabbed infrastructure + whitelabeling form server"
    )
    parser.add_argument(
        "--port",
        type=int,
        default=8777,
        help="Port for local form server (default: 8777)",
    )
    return parser


def main() -> int:
    args = build_parser().parse_args()
    try:
        run_form_server(args.port)
        return 0
    except KeyboardInterrupt:
        return 130
    except Exception as exc:
        print(f"[fatal] {exc}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
